package com.sqlite.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.exp.sign.Wenxue;
import com.exp.sign.BmobUser;
import com.exp.sign.Communicate;

import com.sqlite.greendao.WenxueDao;
import com.sqlite.greendao.BmobUserDao;
import com.sqlite.greendao.CommunicateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wenxueDaoConfig;
    private final DaoConfig bmobUserDaoConfig;
    private final DaoConfig communicateDaoConfig;

    private final WenxueDao wenxueDao;
    private final BmobUserDao bmobUserDao;
    private final CommunicateDao communicateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wenxueDaoConfig = daoConfigMap.get(WenxueDao.class).clone();
        wenxueDaoConfig.initIdentityScope(type);

        bmobUserDaoConfig = daoConfigMap.get(BmobUserDao.class).clone();
        bmobUserDaoConfig.initIdentityScope(type);

        communicateDaoConfig = daoConfigMap.get(CommunicateDao.class).clone();
        communicateDaoConfig.initIdentityScope(type);

        wenxueDao = new WenxueDao(wenxueDaoConfig, this);
        bmobUserDao = new BmobUserDao(bmobUserDaoConfig, this);
        communicateDao = new CommunicateDao(communicateDaoConfig, this);

        registerDao(Wenxue.class, wenxueDao);
        registerDao(BmobUser.class, bmobUserDao);
        registerDao(Communicate.class, communicateDao);
    }
    
    public void clear() {
        wenxueDaoConfig.clearIdentityScope();
        bmobUserDaoConfig.clearIdentityScope();
        communicateDaoConfig.clearIdentityScope();
    }

    public WenxueDao getWenxueDao() {
        return wenxueDao;
    }

    public BmobUserDao getBmobUserDao() {
        return bmobUserDao;
    }

    public CommunicateDao getCommunicateDao() {
        return communicateDao;
    }

}
